#ifndef ERRORES_H
#define ERRORES_H

enum Errores
{
    EXITO,
    ERROR_ABRIENDO_ARCHIVO,
    ERROR_NOMBRE_EDIFICIO,
    ERROR_NOMBRE_MATERIAL,
    ERROR_CANT_PIEDRA,
    ERROR_CANT_MADERA,
    ERROR_CANT_METAL,
    ERROR_CANT_MAXIMA,
    ERROR_COORDENADA_INVALIDA,
    ERROR_COORDENADA_INALCANZABLE,
    ERROR_COORDENADA_INACCESIBLE,
    ERROR_COORDENADA_OCUPADA,
    ERROR_COORDENADA_HABITADA,
    ERROR_COORDENADA_LIBRE,
};

#endif // ERRORES_H
